name: Daily Voting Intentions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scrape_and_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests bs4 pandas pandoc

      - name: Scrape data and save to CSV
        run: python scrapers/wikitable/scrape.py

      - name: Generate HTML table
        run: |
          python -c "
          import pandas as pd
          from datetime import datetime, timedelta
          df = pd.read_csv('voting_intentions.csv')
          df['Poll Date'] = pd.to_datetime(df['Poll Date'], format='%d-%b-%y')
          mask = (df['Poll Date'] >= datetime.now().date() - timedelta(days=7))
          df = df.loc[mask].sort_values(by=['Poll Date'], ascending=False).reset_index(drop=True)
          html_table = pd.DataFrame.to_html(df, index=False)
          with open('table.html', 'w') as f:
              f.write(html_table)
          "

      - name: Convert HTML to Markdown
        uses: pandoc/core@2.0.4
        with:
          from: html
          to: markdown
          args: --wrap=none
          input: ./table.html
          output: ./table.md

      - name: Send email
        uses: dawidd6/action-send-mail@v2.5.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Voting Intentions"
          body: |
            Hi,
            <br><br>
            Here are the latest daily voting intentions from the past week:
            <br><br>
            $(cat table.md)
            <br><br>
            Best regards,
            <br>
            Your friendly neighborhood bot
          to: ${{ secrets.EMAIL_RECIPIENT }}
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: text/html