name: Daily Voting Intentions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scrape_and_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests bs4 pandas

      - name: Scrape data and save to CSV
        run: python scrapers/wikitable/scrape.py

      - name: Send email
        uses: dawidd6/action-send-mail@v3.3.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Voting Intentions"
          body: |
            Hello,

            Enclosed you will find the latest polling results for the 2023 Argentine General Election.

            |     Polling firm     |  Date  |   Party A  |   Party B  |   Party C  |

          run: |
            csv_data = pd.read_csv('./scrapers/wikitable/voting_intentions.csv')
            latest_polls = csv_data.tail(4)
            latest_polls_table = latest_polls[['Polling firm', 'Date', 'Party A', 'Party B', 'Party C']]
            latest_polls_table = latest_polls_table.to_markdown(index=False, tablefmt='pipe')
            echo "::set-output name=latest_polls_table::$latest_polls_table"
          env:
            PYTHONUNBUFFERED: "1"

      - name: Get latest polls table
        id: latest_polls_table
        run: echo "Latest polls table: ${{ steps.send_email.outputs.latest_polls_table }}"
        shell: bash

      - name: Send email with latest polls table
        uses: dawidd6/action-send-mail@v3.3.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Voting Intentions"
          body: |
            Hello,

            Enclosed you will find the latest polling results for the 2023 Argentine General Election.

            ${{ steps.latest_polls_table.outputs.latest_polls_table }}

            Best regards,
            Ryan Mercado
          from: mercadoryan94@gmail.com
          to: mercadoryan94@gmail.com

      - name: Commit and push changes
        if: always()
        run: |
          git config --global user.name "Ryan Mercado"
          git config --global user.email "mercadoryan94@gmail.com"
          git add .
          git commit -m "Update voting intentions"
          git push