name: Daily Voting Intentions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  extract_and_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests bs4 pandas google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Extract data and send email
        run: |
          cd scrapers/wikitable
          python extract_data.py

      - name: Commit and push changes
        if: always()
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "you@example.com"
          git add .
          git commit -m "Update voting intentions"
          git push
          
      - name: Send email
        uses: dawidd6/action-send-mail@v3.3.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Voting Intentions"
          body: "Hello, Enclosed you will find the latest polling results for the 2023 Argentine General Election.\n\nHere are the latest results for the current month:\n\n${{ env.current_month_results }}"
          from: mercadoryan94@gmail.com
          to: mercadoryan94@gmail.com
          attachments: |
            ./scrapers/wikitable/voting_intentions.csv