name: Daily Voting Intentions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scrape_and_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests bs4 pandas

      - name: Scrape data and save to CSV
        run: python scrapers/wikitable/scrape.py

      - name: Parse CSV and send email
        uses: dawidd6/action-send-mail@v3.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Voting Intentions"
          from: "Ryan's Election Bot <mercadoryan94@gmail.com>"
          to: "mercadoryan94@gmail.com"
          body: |
            Hello,

            Enclosed you will find the latest polling results for the 2023 Argentine General Election.

            | Polling Firm | Date       | Party         | % Approval |
            |--------------|------------|---------------|------------|
            {% for poll in polls %}
            | {{ poll['Polling firm'] }} | {{ poll['Date'] }} | {{ poll['Party'] }} | {{ poll['%'] }} |
            {% endfor %}
          attachments: |
            ./scrapers/wikitable/voting_intentions.csv