name: Daily Voting Intentions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scrape_and_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests bs4 pandas

      - name: Scrape data and save to CSV
        run: python scrapers/wikitable/scrape.py

      - name: Send email
        uses: dawidd6/action-send-mail@v3.3.0
        env:
          DATA: |
            $(tail -n 4 ./scrapers/wikitable/voting_intentions.csv | column -t -s ',')
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Daily Voting Intentions"
          body: |
            Hello,
            
            Enclosed you will find the latest polling results for the 2023 Argentine General Election.
            
            <table border="1">
            <tr>
              <th>Polling firm</th>
              <th>Date</th>
              <th>Party A</th>
              <th>Party B</th>
              <th>Party C</th>
            </tr>
            ${{ env.DATA }}
            </table>
            
            Best regards,
            Ryan Mercado
          from: mercadoryan94@gmail.com
          to: mercadoryan94@gmail.com
          attachments: |
            ./scrapers/wikitable/voting_intentions.csv

      - name: Commit and push changes
        if: always()
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "you@example.com"
          git add .
          git commit -m "Update voting intentions"
          git push